extends: airbnb

parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true

rules:
    indent: ["error", 4]
    valid-jsdoc: ["error", {
        prefer: { "return": "returns" }
    }]
